Start testing: Apr 30 12:16 CEST
----------------------------------------------------------
8/8 Testing: TestDosDetector
8/8 Test: TestDosDetector
Command: "/usr/bin/python3.13" "run_tests.py" "/home/dario/universidad/eedd/p5/dos_detector-open_addressing/build//test_dos_detector" "08_tests_dos_detector"
Directory: /home/dario/universidad/eedd/p5/dos_detector-open_addressing
"TestDosDetector" start time: Apr 30 12:16 CEST
Output:
----------------------------------------------------------
Test running: 08_tests_dos_detector/00 ... [31mTest finished with error code -6[0m
test_dos_detector: /home/dario/universidad/eedd/p5/dos_detector-open_addressing/hash.cpp:41: uint64_t pick_at_random(const uint64_t&, const uint64_t&): Assertion `a <= ret_v && ret_v <= b' failed.

Test running: 08_tests_dos_detector/01 ... [31mTest finished with error code -6[0m
test_dos_detector: /home/dario/universidad/eedd/p5/dos_detector-open_addressing/hash.cpp:41: uint64_t pick_at_random(const uint64_t&, const uint64_t&): Assertion `a <= ret_v && ret_v <= b' failed.

0/2 tests passed.
<end of output>
Test time =   0.30 sec
----------------------------------------------------------
Test Failed.
"TestDosDetector" end time: Apr 30 12:16 CEST
"TestDosDetector" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Apr 30 12:16 CEST
